homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: cheesytoenail.duckdns.org
  ssl_certificate: '/ssl/fullchain.pem'
  ssl_key: '/ssl/privkey.pem'
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://home-assistant.io
  #use_x_forwarded_for: True
  #trusted_networks:
  #  - 127.0.0.1
  #  - ::1
  #  - 192.168.1.0/24
  #  - 2001:DB8:ABCD::/48
  # ip_ban_enabled: True
  # login_attempts_threshold: 5

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Sensors
sensor: !include_dir_list sensors

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_list automation

media_player: !include_dir_list media_player

remote: !include_dir_list remote

mqtt: !include_dir_list mqtt