alias: "Turn on Receiver When Sonos Connect Plays"
<<<<<<< HEAD
hide_entity: false
=======
hide_entity: true
>>>>>>> 43e57541a0c09c9daa1997355656e46426a28654
initial_state: true
trigger:
  platform: state
  entity_id: media_player.living_room
  to: playing
condition: 
  condition: state
  entity_id: sensor.harmony
  state: 'PowerOff'
action:
  service: remote.turn_on
  data: 
    activity: 24593350
    entity_id: remote.harmony_hub