alias: "Ungroup/Stop Sonos When Harmony Switches"
<<<<<<< HEAD
hide_entity: false
=======
hide_entity: true
>>>>>>> 43e57541a0c09c9daa1997355656e46426a28654
initial_state: true
trigger:
  platform: state
  entity_id: sensor.harmony
  from: "Sonos - Living Room"
action:
  - service: media_player.sonos_unjoin
    entity_id: media_player.living_room
  - service: media_player.media_stop
    entity_id: media_player.living_room