alias: "Turn off Receiver When Sonos Connect Stops"
hide_entity: false
initial_state: true
trigger:
  entity_id: media_player.living_room
  from: playing
  platform: state
  to: paused
condition: 
  condition: and
  conditions: 
    - condition: state
      entity_id: media_player.living_room
      state: paused
      for: 
        minutes: 10
    - condition: state
      entity_id: sensor.harmony
      state: "Sonos - Living Room"
action: 
  - service: remote.turn_off
    entity_id: remote.harmony_hub
  - service: media_player.sonos_unjoin
    entity_id: media_player.living_room